<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SQI1G9P" ignored="0" name="Default test" tests="1" failures="1" timestamp="2021-12-24T22:40:53 IST" time="2.201" errors="0">
  <testcase name="deleteCustomer" time="2.128" classname="com.w2a.testingfranwork.testcases.DeleteCutsomerTest">
    <failure type="junit.framework.ComparisonFailure" message="cus_JJkvhpS5CYG2zB expected:&amp;lt;cus_JJkvhpS5CYG2zB&amp;gt; but was:&amp;lt;id not matching&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: cus_JJkvhpS5CYG2zB expected:<cus_JJkvhpS5CYG2zB> but was:<id not matching>
at junit.framework.Assert.assertEquals(Assert.java:81)
at com.w2a.testingfranwork.testcases.DeleteCutsomerTest.deleteCustomer(DeleteCutsomerTest.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
</testsuite> <!-- Default test -->
